pipeline {
    agent any

    environment {
        IMAGE_NAME = 'flask-devops-app:latest'
    }

    stages {
        stage('Clone Repo') {
            steps {
                git 'https://github.com/alishahbaz12/devops-tools.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $IMAGE_NAME ./app'
            }
        }

        stage('Run Container (Optional)') {
            steps {
                sh '''
                docker stop flask-container || true
                docker rm flask-container || true
                docker run -d -p 5000:5000 --name flask-container $IMAGE_NAME
                '''
            }
        }

        stage('Post Deployment Test') {
            steps {
                sh 'sleep 10'  // Wait for the container to be fully up
                sh 'python3 ./tests/test_ui.py'
            }
        }
    }
}
